version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./.docker/nginx/config/:/etc/nginx/conf.d/:ro
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - php
      - node
    ports:
      - "3000:3000"
      - "8000:8000"
  node:
    build:
      args:
        NODE_VERSION: '18.16.1' # @see https://nodejs.org/en/download/releases
        CYPRESS_VERSION: '12.17.2' # @see https://www.npmjs.com/package/cypress
        CHROME_VERSION: '115.0.5790.110-1' # @see https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
        FIREFOX_VERSION: '116.0' # @see https://download-installer.cdn.mozilla.net/pub/firefox/releases/
      context: ./.docker/node
    working_dir: /var/www
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/var/www
      - $HOME/.npm:/home/node/.npm
      - $HOME/.cache:/home/node/.cache
    environment:
      DISPLAY:
      MYUID: "${MYUID:-1000}"
      MYGID: "${MYGID:-1000}"
      FONTAWESOME_AUTH_TOKEN: ${FONTAWESOME_AUTH_TOKEN}
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: node
    stdin_open: true
    ipc: host
    tty: true
  php:
    build:
      context: ./.docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - $HOME/.cache:/home/php/.cache
    environment:
      WORKDIR: "/var/www"
      MYUID: "${MYUID:-1000}"
      MYGID: "${MYGID:-1000}"
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=54321
        discover_client_host=1
        idekey=PHPSTORM
        start_with_request=1
      XDEBUG_MODE: debug
      XDEBUG_SESSION: PHPSTORM
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
      - host.docker.internal:host-gateway
    entrypoint: ./.docker/php/scripts/docker-entrypoint.sh
    command: php-fpm
    stdin_open: true
    tty: true
    ipc: host
